version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_VERSION=local
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
